DECLARE @ID AS INT
DECLARE @NAMESURNAME AS VARCHAR(100)
DECLARE @GENDER AS VARCHAR(1)
DECLARE @BIRTHDATE AS DATE
DECLARE @MSG AS VARCHAR(1000)
DECLARE @AGE AS INT
DECLARE CRS CURSOR FOR
SELECT ID,NAMESURNAME,GENDER,BIRTHDATE FROM CUSTOMERS 
WHERE DATEPART(DAY,BIRTHDATE)=DATEPART(DAY,GETDATE())
AND DATEPART(MONTH,BIRTHDATE)=DATEPART(MONTH,GETDATE())
OPEN CRS
FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@GENDER,@BIRTHDATE
WHILE @@FETCH_STATUS =0
BEGIN
SET @MSG ='Sayýn '+@NAMESURNAME
IF @GENDER ='E'
	SET @MSG=@MSG+' Bey;'
ELSE
	SET @MSG=@MSG+' Haným;'
SET @MSG=@MSG+CHAR(13)
SET @AGE =DATEDIFF(YEAR,@BIRTHDATE,GETDATE())
SET @MSG=@MSG+CONVERT(VARCHAR,@AGE)+'. yaþýnýzý kutlar,saðlýklý ömürler dileriz.'
PRINT  @MSG 
FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@GENDER,@BIRTHDATE
END
CLOSE CRS
DEALLOCATE CRS 



