CREATE TABLE #RESULT
(ID	INT,ITEMCODE VARCHAR(100),	ITEMNAME VARCHAR(100),	TOTALSALE_M	 FLOAT, TOTALSALE_W FLOAT,RATIO FLOAT)

INSERT INTO #RESULT (ID,ITEMCODE,ITEMNAME)
SELECT ID,ITEMCODE,ITEMNAME FROM ITEMS 

UPDATE #RESULT SET TOTALSALE_M=
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
WHERE ITEMID=#RESULT.ID
AND U.GENDER='E')

UPDATE #RESULT SET TOTALSALE_W=
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
WHERE ITEMID=#RESULT.ID
AND U.GENDER='K')

UPDATE #RESULT SET RATIO=TOTALSALE_M/TOTALSALE_W

SELECT * FROM #RESULT 
DROP TABLE #RESULT 