CREATE TABLE #RESULT 
(MARKA VARCHAR(100),
OCAK FLOAT,
SUBAT FLOAT,MART FLOAT,	NISAN FLOAT,
MAYIS FLOAT,
HAZIRAN FLOAT,
TEMMUZ FLOAT,	
AGUSTOS FLOAT,
EYLUL FLOAT,
EKIM  FLOAT,
KASIM  FLOAT,
ARALIK FLOAT)


INSERT INTO #RESULT (MARKA)
SELECT DISTINCT BRAND  FROM ITEMS 


UPDATE #RESULT SET OCAK=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=1)

UPDATE #RESULT SET SUBAT=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=2)

UPDATE #RESULT SET MART=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=3)

UPDATE #RESULT SET NISAN=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=4)

UPDATE #RESULT SET MAYIS=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=5)

UPDATE #RESULT SET HAZIRAN=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=6)


UPDATE #RESULT SET TEMMUZ=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=7)

UPDATE #RESULT SET AGUSTOS=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=8)

UPDATE #RESULT SET EYLUL=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=9)

UPDATE #RESULT SET EKIM=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=10)

UPDATE #RESULT SET KASIM=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=11)

UPDATE #RESULT SET ARALIK=(
SELECT 
SUM(OD.LINETOTAL) TOTALSALE 
FROM 
ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
JOIN ITEMS I ON I.ID=OD.ITEMID 
WHERE I.BRAND=#RESULT.MARKA AND MONTH(O.DATE_)=12)

SELECT * FROM #RESULT
DROP TABLE #RESULT

